### ISSUE TITLE
Texture3D WSize not properly set in TextureImpl::getUAV

### ISSUE THREAD

**Issue by Hyiker** [shader-slang/slang-rhi#220]
## Problem

I'm having a demand creating Texture3D with mipmap, which is quite rare. When I tried to create a UAV from a 256x256x256 texture3d with mipCount = 7, dx12 debug layer reported:

> D3D12 ERROR: ID3D12Device::CreateUnorderedAccessView: The Dimensions of the View are invalid. MipSlice (value = 2) must be between 0 and MipLevels-1 of the Texture Resource, 7, inclusively. FirstWSlice (value = 0) must be between 0 and the Depth size of the Mip Level, 63, inclusively. With the current FirstWSlice, WSize (value = 256) must be between 1 and 64, or -1 to default to all slices from MipSlice, inclusively, in order that the View fit on the Texture. [ STATE_CREATION ERROR #345: CREATEUNORDEREDACCESSVIEW_INVALIDDIMENSIONS]

## Cause

I was running my algorithm on [Falcor](https://github.com/NVIDIAGameWorks/Falcor), with slang version 2023.5.8, keyword search showed that WSize is set in slang-rhi/src/d3d12/d3d12-texture.cpp:

```cpp
case TextureType::Texture3D:
        viewDesc.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE3D;
        viewDesc.Texture3D.MipSlice = range.mipLevel;
        viewDesc.Texture3D.FirstWSlice = range.baseArrayLayer;
        viewDesc.Texture3D.WSize = m_desc.size.depth;
        break;
```

where WSize is set to texture depth, as a constant in this function(256 in my case), which should be the depth corresponding to the texture mipmap level(64, in my case). In the latest version of slang-rhi, [src/d3d12/d3d12-texture.cpp](https://github.com/shader-slang/slang-rhi/blob/ee449ba6a400aa12b23e960b93e8abc6c80bff4f/src/d3d12/d3d12-texture.cpp#L233) hasn't changed yet.

## Possible solution

[Microsoft document](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_tex3d_uav) indicates that:

> WSize
> The number of depth slices.
> Set to -1 to indicate all the depth slices from FirstWSlice to the last slice.

Otherwise, API should calculate the WSize for the specific mipLevel or provides an option for user to manually set this parameter. Anyway, I prefer the -1 solution.

**Comment by bmillsNV** [comment]
This might have been fixed in TOT. Looks like this is currently using a version of Slang ~2 years old.

**Comment by Hyiker** [comment]
> Hi [@Hyiker](https://github.com/Hyiker) , I've started investigating the issue. Do you have a minimal shader that reproduces the issue or have a shader code snippet related to the issue? I'd like to try reproducing the issue such that I can verify possible solutions.

Thanks for your attention! Surprisingly, I found f7a14c4 commited 20 days ago may have already fixed the problem with 

```cpp
viewDesc.Texture3D.WSize = max(m_desc.size.depth >> range.mipLevel, 1);
```

This should be the proper way to set WSize, and the 3d mipmap test `texture-layout-3d-mip` now behaves correctly. I'll close this issue if there's no other questions.

**Comment by sricker-nvidia** [comment]
Thanks for sharing that commit. However, I suspect that something is still incorrect with the viewDesc.Texture3D.WSize logic.

I tried stepping through the texture-layout-3d-mip test case, and it never hits the `viewDesc.Texture3D.WSize = max(m_desc.size.depth >> range.mipLevel, 1);` line in d3d12-texture.cpp. I even reverted the code back to `viewDesc.Texture3D.WSize = m_desc.size.depth;` and the test still seems to pass, so I'm not sure if texture-layout-3d-mip is a good test of correctness.

Was there a different test that was used to generate the original dx12 debug layer print out above? I noticed that the mip level was 2 (MipSlice (value = 2)) in that error, but the texture-layout-3d-mip test case only seems to use a mip level of 0 and 1, so I'm wondering if there's something else I can test with.

I suspect that viewDesc.Texture3D.WSize should actually be set to something like range.layerCount based on the description of WSize shared above (although that may require some additional updates in other parts of the code). For example, with a 256x256x256 texture, using a mip level of 1, and a FirstWSlice of 64, max(m_desc.size.depth >> range.mipLevel, 1) would set WSize = 128, but I believe this would be illegal as there are only 64 depth slices from FirstWSlice to the last slice (including FirstWSlice).

Let me know what you think.

**Comment by Hyiker** [comment]
After digging the source code, I've found that tests don't actuall call `TextureImpl::getUAV`. And the fact is that `TextureImpl::getUAV` seems to be a platform specified function, which is called only in `BindingDataBuilder::bindAsValue`. It's not exposed as public, making it hard to construct short code snippet for reproducing the problem.

I attemptde to use a hacky way like calling `getUAV` in `TextureViewImpl::TextureViewImpl` but `TextureViewImpl::m_texture` is alway nullptr preventing me doing so(And I failed to find out the reason). I encountered this problem in [Falcor](https://github.com/NVIDIAGameWorks/Falcor), but I'm not so familiar with raw `slang-rhi` or `slang-gfx` function calls, I could provide you with a minimal reproduce in Falcor if necessary.

Back to the problem, I think you're right, using `max(m_desc.size.depth >> range.mipLevel, 1)` is not a proper way if `FirstWSlice != 0`.
Alternatives:

- Calculate this value carefully
- Use user specified value
- Use `-1` as mentioned in the doc

**Comment by sricker-nvidia** [comment]
Posting an update. I've been able to create a new unit test that exercises the problematic code path. Setting up a 3D texture sized 16x16x16 with mip levels 8x8x8, 4x4x4, 2x2x2, and 1x1x1 and trying to create and use a textureView using a subresource range of { 1 /*mipLevel*/, 4 /*mipLevelCount*/, 1 /*baseArrayLayer or FirstWSlice*/, 1 /*layerCount*/} and can reproduce an error message similar to the original D3D12 ERROR:

`D3D12 ERROR: ID3D12Device::CreateUnorderedAccessView: The Dimensions of the View are invalid. MipSlice (value = 1) must be between 0 and MipLevels-1 of the Texture Resource, 4, inclusively. FirstWSlice (value = 1) must be between 0 and the Depth size of the Mip Level, 7, inclusively. With the current FirstWSlice, WSize (value = 16) must be between 1 and 7, or -1 to default to all slices from MipSlice, inclusively, in order that the View fit on the Texture. [ STATE_CREATION ERROR #345: CREATEUNORDEREDACCESSVIEW_INVALIDDIMENSIONS]`

I've added a new depthSlices member to SubresourceRange and now set `viewDesc.Texture3D.WSize = range.depthSlices;` instead of using m_desc.size.depth and things work as expected.

I need to clean up the new unit tests a bit and then I will create a PR to address the issue and add the new unit tests. I should be able to get something ready at some point Monday.

**Comment by skallweitNV** [comment]
@Hyiker you mentioned that you ran into this in Falcor?
Note that Falcor uses `slang-gfx` (the "old" abstraction layer in the slang repository) and not `slang-rhi` which we started for our future projects.

**Comment by Hyiker** [comment]
> [@Hyiker](https://github.com/Hyiker) you mentioned that you ran into this in Falcor? Note that Falcor uses `slang-gfx` (the "old" abstraction layer in the slang repository) and not `slang-rhi` which we started for our future projects.

It was my mistake, the git submodule of latest version slang led me to slang-rhi here.  Indeed, in the slang v2023.5.8, this problem is directly caused by `tools/gfx/d3d12/d3d12-device.cpp` line 1570. The root cause is the same, thanks for your correction!

**Comment by Hyiker** [comment]
Appreciate your discussion and work! I'll close this issue by now.
